server:
  port: 9001
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
spring:
  application:
    name: cloud-gateway
  profiles:
    active: prod
  cloud:
    gateway:
      # 这是自动负责均衡
#      discovery:
#        locator:
#          enabled: true
      # 手动负载均衡
      routes:
        - id: zb-server-route
          uri: lb://zb-server
          predicates:
            - Path=/zb/**
          filters:
            - StripPrefix=1
    nacos:
      discovery:
          #注册中心
        server-addr: localhost:8848
        # 配置中心
      config:
        server-addr: localhost:8848
        file-extension: yaml

