server:
  port: 9001
spring:
  application:
    name: cloud-gateway
  profiles:
    active: prod
  cloud:
    gateway:
      routes:
        - id: zb-server-route
          uri: lb://zb-server
          predicates:
            - Path=/*
    nacos:
      discovery:
          #注册中心
        server-addr: localhost:8848
        # 配置中心
      config:
        server-addr: localhost:8848
        file-extension: yaml

