server:
  port: 9003
spring:
  application:
    name: solr-server
  profiles:
    active: prod
  cloud:
    nacos:
      discovery:
          #注册中心
        server-addr: localhost:8848
        # 配置中心
      config:
        server-addr: localhost:8848
        file-extension: yaml

